[build]
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"

# ISR configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"
