# Netlify configuration file

[build]
  command = "npm run build"
  publish = "dist"

# Force no caching for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Force no caching for Supabase data
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Add cache control but allow browser caching for static assets
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirect all 404s to index for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variable configuration
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Function configuration
[functions]
  directory = "netlify/functions"
